// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXo474xGdVwo7TkAudMZIJ1fm7o1OkumI',
    appId: '1:791631137491:web:fb71f9a5fa7b4ec5a1a226',
    messagingSenderId: '791631137491',
    projectId: 'amblyopie',
    authDomain: 'amblyopie.firebaseapp.com',
    storageBucket: 'amblyopie.firebasestorage.app',
    measurementId: 'G-GENV6XW1C4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaeXx_OLSJH2yu5_RLeUKXW1aX0oYsNHQ',
    appId: '1:791631137491:android:8d26b7e4ed303297a1a226',
    messagingSenderId: '791631137491',
    projectId: 'amblyopie',
    storageBucket: 'amblyopie.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoKOSEYHEHY64RgZ89YYjufd8--pCFPSY',
    appId: '1:791631137491:ios:a9ab07404355659fa1a226',
    messagingSenderId: '791631137491',
    projectId: 'amblyopie',
    storageBucket: 'amblyopie.firebasestorage.app',
    iosBundleId: 'com.example.amblyopie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoKOSEYHEHY64RgZ89YYjufd8--pCFPSY',
    appId: '1:791631137491:ios:a9ab07404355659fa1a226',
    messagingSenderId: '791631137491',
    projectId: 'amblyopie',
    storageBucket: 'amblyopie.firebasestorage.app',
    iosBundleId: 'com.example.amblyopie',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXo474xGdVwo7TkAudMZIJ1fm7o1OkumI',
    appId: '1:791631137491:web:39d090ee9434e473a1a226',
    messagingSenderId: '791631137491',
    projectId: 'amblyopie',
    authDomain: 'amblyopie.firebaseapp.com',
    storageBucket: 'amblyopie.firebasestorage.app',
    measurementId: 'G-86255EHNMJ',
  );

}